- name: Deploy via SFTP
  env:
    IONOS_HOST: ${{ secrets.IONOS_HOST }}
    IONOS_USER: ${{ secrets.IONOS_USER }}
    IONOS_PASS: ${{ secrets.IONOS_PASS }}
    IONOS_PATH: ${{ secrets.IONOS_PATH }}
  run: |
    lftp -c "
    open -u $IONOS_USER,$IONOS_PASS sftp://$IONOS_HOST
    mirror -R --verbose \
      --exclude .logs/ \
      --exclude access.log \
      --exclude access.log.* \
      --exclude sftp.log \
      --exclude sftp.log.* \
      --exclude traffic.db \
      ./ $IONOS_PATH
    "
